---
groups:
- name: OONI Alerts
  rules:
  - alert: NASBackupSilent
    expr: time() - push_time_seconds{exported_instance="hellais-nas"} > 16 * 3600
    annotations:
      summary: 'hellais-nas is silent for {{ $value | humanizeDuration }}'

  - alert: NASRsyncFailure
    expr: rsync_returncode{exported_instance="hellais-nas"} != 0
    for: 16h # rsync is launched at 08:00 and 22:00, that's 14h and 10h gap
    annotations:
      summary: 'hellais-nas `rsync` exitcode: {{ $value }}'

  - alert: MetaDBS3Silent
    expr: round(time() - metadb_wal_ship_time, 3600) > 30 * 3600
    annotations:
      summary: 'MetaDB `archive_command` is silent for {{ $value | humanizeDuration }}'

  - alert: MetaDBS3Failure
    expr: metadb_wal_ship_success != 1
    for: 30m
    annotations:
      summary: 'MetaDB `archive_command` fails for 30m+.'

  # Some nodes may have it broken, but it usually works, here is expr to validate it.
  # expr: (max without (device) (node_seeksample_timestamp{job="node"}) or up{job="node"}) == 1
  - alert: DiskStuck
    expr: node_time - ignoring(device) group_right node_seeksample_timestamp > 240
    annotations:
      summary: '{{ $labels.instance }} has `{{ $labels.device }}` silent for {{ $value | humanizeDuration }}'

  - alert: MirrorDiverged
    expr: scalar(max(ooni_web_mtime)) - ooni_web_mtime > 0
    for: 11m # job_name=ooni-web scrape_interval is 5m, 8m10s is still "ordinary" delay
    annotations:
      summary: 'Mirror {{ $labels.instance }} lags by {{ $value | humanizeDuration }}'
      description: '{{ if eq $labels.instance "ooni.torproject.org:443" }}Run `make update-site`.{{ end }}'

  - alert: AirflowDagFailed
    expr: airflow_7d_dag_failed_count > 0
    annotations:
      summary: '{{ $value }} DAG `{{ $labels.dag }}` failures last week'
      description: >
        Last `{{ $labels.dag }}` failure {{ (printf "round(time() - airflow_7d_dag_failed_last_time_seconds{dag='%s'}, 3600)" $labels.dag) | query | first | value | humanizeDuration | reReplaceAll " 0m 0s$" "" }} ago.
        Yours <http://127.0.0.1:8080/admin/airflow/tree?dag_id={{ $labels.dag }}|airflow>.

  - alert: AirflowTaskFailed
    expr: airflow_7d_task_failed_count > 0
    annotations:
      summary: '{{ $value }} task `{{ $labels.task }}` failures last week'
      description: >
        Last `{{ $labels.task }}` failure {{ (printf "round(time() - airflow_7d_task_failed_last_time_seconds{dag='%s',task='%s'}, 3600)" $labels.dag $labels.task) | query | first | value | humanizeDuration | reReplaceAll " 0m 0s$" "" }} ago.

  - alert: SlacktopusGone
    expr: time() - slacktopus_ctcp_pong_time > 660 # it's randomized */5 crontab
    annotations:
      summary: Slacktopus is gone for {{ $value | humanizeDuration }} (maybe that's just darkk's WeeChat)
...
