- name: restart nginx
  service: name=nginx state=restarted
- name: restart jupyter
  systemd: name=jupyter.service state=restarted
- name: reload jupyter
  systemd: name=jupyter.service state=reloaded
