---
- import_playbook: ansible-version.yml

- host: fastpath.ooni.nu
  tags: 'collector'
  tasks:
    - name: slurp the ssh key from the fastpath
      slurp:
        src: /var/lib/fastpath/ssh/id_ed25519.pub
      register: edkey

    - name: slurp the ssh key from the fastpath
      set_fact:
        ssh_key: "{{ edkey['content'] | b64decode }}"

- hosts: mia-ps-test.ooni.nu
  tags: test
  roles:
    - role: docker
      tags: base
    - role: letsencrypt
      tags: base
      letsencrypt_domains:
        - "mia-ps-test.ooni.nu"
        - "ps-test.ooni.io"
        # XXX legacy addresses. Deprecate as soon as traffic drops to zero
        - "events.proteus.test.ooni.io"
        - "registry.proteus.test.ooni.io"
    - role: ooni-bouncer
      tags:
        - service
        - bouncer
    - role: ooni-collector
      with_nginx: no
      tags:
        - service
        - collector
    - role: probe-services
      tags: ps

- hosts: ams-ps.ooni.nu
  roles:
    - role: docker
    - role: letsencrypt
      expand: yes
      tags: tls
      letsencrypt_domains:
        - "ams-ps.ooni.nu"
        - "ps.ooni.io"
        - "bouncer.ooni.io"
        - "collector.ooni.io"
        - "registry.ooni.io"
        - "orchestrate.ooni.io"
        # Legacy addresses
        - "events.proteus.ooni.io"
        - "registry.proteus.ooni.io"
    - role: ooni-bouncer
      tags:
        - service
        - bouncer
    - role: ooni-collector
      tags:
        - service
        - collector
    - role: probe-services
      tags: ps
    - role: onion-service
      tags: tor
      onion_services:
      - "{{ bouncer_service_v2 }}"

- hosts: mia-ps.ooni.nu
  roles:
    - role: docker
      tags: base
    - role: letsencrypt
      tags: base
      letsencrypt_domains:
        - "mia-ps.ooni.nu"
    - role: ooni-bouncer
      tags:
        - service
        - bouncer
    - role: ooni-collector
      tags:
        - service
        - collector
    - role: probe-services
      tags: ps

- hosts: hkg-ps.ooni.nu
  roles:
    - role: docker
      tags: base
    - role: letsencrypt
      tags: base
      letsencrypt_domains:
        - "hkg-ps.ooni.nu"
    - role: ooni-bouncer
      tags:
        - service
        - bouncer
    - role: ooni-collector
      tags:
        - service
        - collector
    - role: probe-services
      tags: ps
