---

# FIXME: do we _really_ need nginx in front of the collector?
- template: src=ngx-ooni-backend-web dest=/etc/nginx/sites-enabled/ooni-backend-web
  notify: reload nginx

# FIXME what is this? Do we need this for the collector?!
- name: docker network for backend
  docker_network:
    name: msm
    driver_options:
      com.docker.network.bridge.name: brmsm
    ipam_options:
      subnet: 172.25.232.0/24
      gateway: 172.25.232.1

# FIXME this is not the correct procedure to start it up
# at the moment this is copied from ooni-measurements
- name: ooni-backend webservice
  docker_container:
    image: openobservatory/ooni-collector:{{ ooni_collector_tag }}
    name: ooni-collector
    hostname: ooni-collector
    networks: [{name: msm, ipv4_address: '{{ ooni_collector_tag }}'}]
    purge_networks: true
    env:
      APP_ENV: production
    command: '/usr/local/bin/oonib -c {{ ooni_collector_config_path }}'
    user: "{{ passwd.ooni_backendweb.id }}:{{ passwd.ooni_backendweb.id }}"
    restart_policy: unless-stopped
